infoteka/en/urls.py
from django.urls import path

from . import views

app_name = 'en'
urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),

    # Organization
    path('organization/publicis/', views.PublicisHome.as_view(), name='publicisHome'),
    path('organization/publiciscommerce', views.PublicisCommerceHome.as_view(), name='publicisCommerceHome'),
    path('organization/structure', views.PublicisStructureHome.as_view(), name='publicisStructureHome'),
    path('organization/janus', views.JanusHome.as_view(), name='janusHome'),


    ####################
    # TOOLS & SERVICES
    ####################

    # Travel Policy
    path('tools_services/travelpolicy', views.TravelPolicyHome.as_view(), name='TravelPolicyHome'),
    path('tools_services/travelpolicy/traveler', views.TravelPolicyTravellerHome.as_view(), name='TravelPolicyTravellerHome'),
    path('tools_services/travelpolicy/faq', views.TravelPolicyFaqHome.as_view(), name='TravelPolicyFaqHome'),
    path('tools_services/travelpolicy/planning', views.TravelPolicyPlanningHome.as_view(), name='TravelPolicyPlanHome'),
    path('tools_services/travelpolicy/expenses', views.TravelPolicyExpensesHome.as_view(), name='TravelPolicyExpensesHome'),
    ]

infoteka/infoteka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from en import views


urlpatterns = [
    path('', RedirectView.as_view(url='en/')),
    path('en/', include('en.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

infoteka/en/models.py
from django.db import models

# Create your models here.

infoteka/en/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


# ORGANIZATION VIEWS

class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'en/index.html'


class PublicisHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/organization/publicis.html'


class PublicisCommerceHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/organization/publicis_commerce.html'


class PublicisStructureHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/organization/structure.html'


class JanusHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/organization/janus.html'



# TOOLS AND SERVICES VIEWS

class TravelPolicyHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/tools_services/travel_policy/travel_policy.html'

class TravelPolicyTravellerHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/tools_services/travel_policy/travel_policy_traveler.html'

class TravelPolicyFaqHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/tools_services/travel_policy/travel_policy_faq.html'

class TravelPolicyPlanningHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/tools_services/travel_policy/travel_policy_planning.html'

class TravelPolicyExpensesHome(LoginRequiredMixin, TemplateView):
    template_name = 'en/tools_services/travel_policy/travel_policy_expenses.html'

infoteka/en/templates/en/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'en/css/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Infoteka</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'en/images/favicon.png' %}" />
</head>

<body>

    <!-- NAVIGATION -->


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container d-flex justify-content-between">

            <a class="navbar-brand" href="{% url 'en:index' %}"><img class="mb-4" style="margin-bottom: 0!important;" src="{% static 'en/images/book.png' %}" alt="" width="28" height="28"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="#">Onboarding+</a>
                    </li>

                    <!-- ORAGNIZATION -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Organization
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'en:publicisHome' %}">Publicis Groupe</a>
                            <a class="dropdown-item" href="{% url 'en:publicisCommerceHome' %}">Publicis Commerce</a>
                            <a class="dropdown-item" href="{% url 'en:janusHome' %}">Janus</a>
                            <a class="dropdown-item" href="#">Strategy</a>
                            <a class="dropdown-item" href="{% url 'en:publicisStructureHome' %}">Structure</a>
                            <a class="dropdown-item" href="#">Back-office</a>
                            <a class="dropdown-item" href="#">Credentials</a>
                            <a class="dropdown-item" href="#">Corporate Identity</a>
                        </div>
                    </li>
                    <!-- EOF ORAGNIZATION -->

                    <!-- TOOLS & SERVICES -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tools & Services
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Goals settings and performance review</a>
                            <a class="dropdown-item" href="#">Work Time and absence management</a>
                            <a class="dropdown-item" href="{% url 'en:TravelPolicyHome' %}">Travel policy</a>
                            <a class="dropdown-item" href="#">Finance</a>
                            <a class="dropdown-item" href="#">Human resources</a>
                            <a class="dropdown-item" href="#">Hardware & Software</a>
                            <a class="dropdown-item" href="#">Benefits</a>
                            <a class="dropdown-item" href="#">Social Benefit Fund</a>
                        </div>
                    </li>
                    <!-- EOF TOOLS & SERVICES -->

                    <!-- WORKSPACE -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Workspace
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Offices</a>
                            <a class="dropdown-item" href="#">Conference rooms</a>
                            <a class="dropdown-item" href="#">Office supplies</a>
                        </div>
                    </li>
                    <!-- EOF WORKSPACE -->

                </ul>

            </div>
            {% if user.is_authenticated %}
                Hi {{ user.username }}&nbsp;<a href="{% url 'logout' %}">Logout</a>
            {% endif %}
        </div>

    </nav>


    <!-- END OF NAVIGATION -->
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

infoteka/en/templates/en/footer.html
<footer class="container">
    <hr>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2019 Publicis Commerce</p>
</footer>

infoteka/en/templates/en/index.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}
<main role="main">

  <section class="text-center">
    <div class="container">

      <br>
      <img width="30%" alt="Thumbnail [100%x225]" src="{% static 'en/images/landing_main3.jpg' %}">
      <br><br>
      <hr class="landing-hr">
 
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 box-shadow" style="border: none;">
            <img class="card-img-top" alt="Thumbnail [100%x225]" src="{% static 'en/images/landing_1.jpeg' %}">
            <div class="card-body">
              <p class="card-text">Nothing is impossible, even finding your way around a large company when you’ve just
                started here or when something has changed.</p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow" style="border: none;">
            <img class="card-img-top" alt="Thumbnail [100%x225]" src="{% static 'en/images/landing_2.jpeg' %}">
            <div class="card-body">
              <p class="card-text">Infoteka is one answer to all possible questions, because your head is meant for the
                projects we work on, not for memorizing lots of formalities.</p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow" style="border: none;">
            <img class="card-img-top" alt="Thumbnail [100%x225]" src="{% static 'en/images/landing_3.jpeg' %}">
            <div class="card-body">
              <p class="card-text">Treat Infoteka as a primary care doctor. Always visit her first when a question
                bothers you. You can follow all the changes and new developments to keep up to date here.</p>
            </div>
          </div>
        </div>

      </div>


    </div>
  </section>

</main>

{% endblock content %}

infoteka/en/templates/en/organization/janus.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <h1 class="display-4">Janus</h1>
    <p class="lead">
        Janus is our Groupe​ guide on operations, procedures and behaviours.<br><br>
        Its about compliance, rules, code of conduct and, as such, it remains a restrictive and binding framework for
        the whole Groupe. In a world of defiance of corporations, of suspicion towards financial systems, etc.,
        compliance and good governance are paramount to our credibility and vital to gain all our stakeholders'
        confidence.<br><br>
        We urge all and everyone to read Janus and to disseminate it, as all entities across the Groupe must abide by
        these rules.
    </p>
    <br>
    <h2 class="">Volume I</h2>
    <p class="lead">Is about general standards, and is considered mandatory to get acquainted with:<br>
        <a data-interception="on" href="https://1drv.ms/b/s!AqG-BGp6EqHfc0OY2FPaTNie6pE">Polish version</a><br>
        <a data-interception="on" href="https://1drv.ms/b/s!AqG-BGp6EqHfdOsSKBOsgG9P1K0">English version</a>
    </p>
    
    <br>
    <h2 class="">Volume II</h2>
    <p class="lead">Provide an accounting policies and procedures framework. Aimed for financial and accounting teams:<br>
        <a data-interception="on" href="https://1drv.ms/b/s!AqG-BGp6EqHfch2JWQ2xUFjY0Fo">English version</a>
    </p>
</div>
<br>

{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/organization/publicis.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}
<div>
    <img src="{% static 'en/images/publicis/lion.jpg' %}" alt="" width="100%">
</div>
<br>
<div class="container">
    <h1 class="display-4">Publicis Groupe</h1>
    <p class="lead">
        Publicis was founded in France by Marcel Bleustein-Blanchet in 1926. He was an extraordinary man who also fought
        in the Second World War and pioneered radio advertising in France.</n>
        <br><br>The company’s origins were quite modest – it all started in a Paris apartment. Today, after over 90
        years of development, the company is now the group – Publicis Groupe – the 3rd largest communication group in
        the world.
    </p>
    <br>
    <h2 class="">Holding of the year 2017</h2>
    <p class="lead">For the first time in the 17-year history of the magazine "Media and Marketing Polska", Publicis was
        named "Holding of the Year". The editors clearly rated Publicis Groupe very highly. This special title was
        testament to our great business results and positive transformations in terms of cooperation between agencies,
        as well as the quality of our services and achievements in the digital field. That was indeed quite something!
    </p>
    <br>
    <h2 class="">Power of ONE</h2>
    <p class="lead">The philosophy of the group is THE POWER OF ONE. All units should act in synergy and complement
        their competences to build real value for the client by providing the best business and communication
        solutions.<br><br>The main areas of activity are: communication strategy, film production, media planning and
        buying, e-commerce, performance marketing, content marketing, public relations, public affairs, CSR, and
        consulting services in the field of business transformation.
    </p>
    <br>
    <img src="{% static 'en/images/publicis/agencyMap.png' %}" alt="">
    <br>
    <h2 class="">Publicis Communication</h2>
    <p class="lead">Publicis Communications is a centre of creative expertise and Publicis’ real right hand in
        advertising.The main areas of our activity are creation, film production, public relations and public affairs.
        Our job is to attract the greatest talents in the industry and provide clients with effective solutions in the
        field of communication in marketing. <br><br>We create tailor-made answers based on consumer insights, brand
        knowledge
        and creative concepts, with added data and technology support. PC employs 30,000 experts in 100 branches across
        20 countries.<br><br>
        In Poland we operate the agencies: Saatchi & Saatchi IS, Leo Burnett, Publicis Worldwide, MSL, Prodigious,
        Marcel and Fallon.
    </p>
    <br>
    <h2 class="">Publicis Media</h2>
    <p class="lead">In terms of turnover Publicis Media represents the leading large group of agencies in Poland (RECMA
        ranking). It has also received the title Most Desired Employer (Antal company ranking).<br><br>
        Its main areas of activity are: communication strategy, media planning and buying, performance marketing,
        analytics and research, technology and data management, content marketing and business transformation. Thanks to
        the continuous cooperation of its different agencies, which make use of their varied resources and expert
        knowledge, the group guarantees easy access to all of its key competences and services to meet clients' business
        needs.
        PM employs 18,000 experts in 285 branches across 80 markets.<br><br>
        In Poland the following agencies operate within its framework: Starcom, Zenith, Digitas, Spark, Blue 449,
        Performics and LiquidThread.
    </p>
    <br>
    <h2 class="">Publicis Health</h2>
    <p class="lead">The largest worldwide network of agencies specialising in the healthcare sector and providing
        services to biomedical companies.
        It offers innovative solutions for communication in marketing, brand building strategies and increasing market
        access.<br><br>
        The ever-evolving healthcare environment requires flexibility and the ability to react quickly. The innovative
        solutions provided by Publicis Health allow our clients’ brands to maximize their potential and enhance their
        business results.
        There are around 5,500 people in the PSHC team, in 60 offices across 10 countries.<br><br>
        The network includes the following brands: Saatchi & Saatchi Wellness, Digitas Health LifeBrands, Publicis
        LifeBrands, Razorfish Health,
        Heartbeat Ideas, Discovery Worldwide, Insync Customer Insights, Public Health Media, Publicis Touchpoint
        Solutions, Publicis Health Media, Publicis Resolute, Langland, Evolvr, Maxcess and Verilogue.
    </p>
    <br>
    <h2 class="">Publicis Sapient</h2>
    <p class="lead">Publicis Sapient is the most advanced digital transformation platform in the world. It specialises
        in consultancy and implementing digital and technological solutions in business. <br><br>Companies must be modern and
        competitive to meet today's market requirements, and this involves the adoption of a completely new thinking
        about business – digital transformation. Publicis Sapient, building a business platform from scratch, changes
        both a client's business strategy and his operational activity, making possible improvements in performance and
        his readiness for further development and innovation. <br><br>There are 17,000 people employed by PS in 100 offices
        across 50 countries. This includes SapientRazorfish and Sapient Consulting.
    </p>
    <br>
</div>

{% include 'en/footer.html' %}

{% endblock content %}

infoteka/en/templates/en/organization/publicis_commerce.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <h1>Publicis Commerce</h1>
    <iframe
        src="https://onedrive.live.com/embed?resid=DFA1127A6A04BEA1%21107&amp;authkey=%21ABEeQTqBJyeGU_o&amp;em=2&amp;wdAr=1.7777777777777777"
        width="1186px" height="691px" frameborder="0">To jest osadzony dokument pakietu <a target="_blank"
            href="https://office.com">Microsoft Office</a> obsługiwany przez aplikację <a target="_blank"
            href="https://office.com/webapps">Office Online</a>.</iframe>
</div>

{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/organization/structure.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <h1>Publicis Commerce Structure</h1>
    <iframe
        src="https://onedrive.live.com/embed?cid=DFA1127A6A04BEA1&amp;resid=DFA1127A6A04BEA1%21106&amp;authkey=AMQw9YuB2w55tnM&amp;em=2&amp;wdAr=1.7777777777777777"
        width="1186px" height="691px" frameborder="0">To jest osadzony dokument pakietu <a target="_blank"
            href="https://office.com">Microsoft Office</a> obsługiwany przez aplikację <a target="_blank"
            href="https://office.com/webapps">Office Online</a>.</iframe>
</div>

{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/tools_services/travel_policy/travel_policy.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <h1 class="display-4">Travel Policy</h1>
    <p class="lead">
        << General Info on Travel Policy >> <br> <br>
        For most common questions, please refer to <a href="{% url 'en:TravelPolicyFaqHome' %}">Travel Policy FAQ</a>.
    </p>
    <br>
    <hr>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'en:TravelPolicyTravellerHome' %}">Traveller setup</a></h5>
                  <p class="card-text">Everything you need to do, in order to book your travels in our company.</p>
                </div>
              </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'en:TravelPolicyPlanHome' %}">Planning business trip</a></h5>
                  <p class="card-text">Actions that you need to complete, in order to prepare business trip.</p>
                </div>
              </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'en:TravelPolicyExpensesHome' %}">Expense account</a></h5>
                  <p class="card-text">How to get refund for expenses you had during your trip.</p>
                </div>
              </div>
        </div>
      </div>
</div>
<br>

{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/tools_services/travel_policy/travel_policy_expenses.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <p class="lead">Return to <a href="{% url 'en:TravelPolicyHome' %}">Travel Policy</a></p>

</div>
<br>



{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/tools_services/travel_policy/travel_policy_faq.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <p class="lead">Return to <a href="{% url 'en:TravelPolicyHome' %}">Travel Policy</a></p>

</div>
<br>



{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/tools_services/travel_policy/travel_policy_planning.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}


<div class="container">
    <br>
    <p class="lead">Return to <a href="{% url 'en:TravelPolicyHome' %}">Travel Policy</a></p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#dietCalculator">Diet
        Calculator</button>







    <!-- Diet Calculator PopUp -->
    <div class="modal fade" id="dietCalculator" tabindex="-1" role="dialog" aria-labelledby="dietCalculatorTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="dietCalculatorLongTitle">Diet Calculator</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table style="border-collapse:separate;border-spacing:0 5px;">
                        <tr>
                            <td>Country:&nbsp;</td>
                            <td><select name="Country" id="dropCountry"></select></td>
                        </tr>
                        <tr>
                            <td>From:&nbsp;</td>
                            <td><input type="datetime-local" name="dateFrom" id="dateFrom"></td>
                        </tr>
                        <tr>
                            <td>To:&nbsp;</td>
                            <td><input type="datetime-local" name="dateTo" id="dateTo"></td>
                        </tr>
                    </table>
                    <hr>
                    <p class='lead'>Number of meals</p>
                    <table>
                        <tr>
                            <td>Breakfasts:</td>
                            <td><input type="number" name="breakfastNumber" id="breakfastNumber"></td>
                        </tr>
                        <tr>
                            <td>Lunches:</td>
                            <td><input type="number" name="lunchNumber" id="lunchNumber"></td>
                        </tr>
                        <tr>
                            <td>Dinners:</td>
                            <td><input type="number" name="dinnerNumber" id="dinnerNumber"></td>
                        </tr>
                    </table>
                    <hr>
                    <p class='lead'>Diet elements</p>
                    <table>
                        <tr>
                            <td>Diet for full days</td>
                            <td id="fullDayDiet"></td>
                        </tr>
                        <tr>
                            <td>Diet for partial day</td>
                            <td id="partialDayDiet"></td>
                        </tr>
                        <tr>
                            <td>Breakfasts</td>
                            <td id="breakfastsDiet"></td>
                        </tr>
                        <tr>
                            <td>Lunches</td>
                            <td id="lunchDiet"></td>
                        </tr>
                        <tr>
                            <td>Dinners</td>
                            <td id="dinnerDiet"></td>
                        </tr>
                    </table>
                    <hr>
                    <p class='lead'>Final DIET: <span id='finalDiet'></span></p>
                </div>

            </div>
        </div>
    </div>
</div>
<br>

<script>var json_url = "{% static 'en/js/diet_calculator.json' %}";</script>
<script src="{% static 'en/js/diet_calculator.js' %}"></script>

{% include 'en/footer.html' %}
{% endblock content %}

infoteka/en/templates/en/tools_services/travel_policy/travel_policy_traveler.html
{% extends 'en/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <br>
    <p class="lead">Return to <a href="{% url 'en:TravelPolicyHome' %}">Travel Policy</a></p>

    

</div>
<br>


<!-- Button trigger modal -->


{% include 'en/footer.html' %}
{% endblock content %}